name: Build with ESP-IDF v4.4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Arduino build ESP32
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32
        command: "idf.py set-target esp32 && idf.py build"

    - name: Arduino build ESP32-S3
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32s3
        command: "idf.py set-target esp32s3 && idf.py build"

    - name: Arduino build ESP32-C3
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: release-v4.4
        target: esp32c3
        command: "idf.py set-target esp32c3 && idf.py build"

